# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

def shared_pods
  
  # Pod setting for Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'SwiftyJSON'
end

target 'AppStore' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for AppStore
  shared_pods
end

target 'Develop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Develop
  shared_pods
end

target 'Staging' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Staging
  shared_pods
end
